apiVersion: apps/v1
kind: Deployment
metadata:
  name: churnset-deployment
  namespace: churnset-namespace
  labels:
    app: churnset-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churnset-app
  template:
    metadata:
      labels:
        app: churnset-app
    spec:
      containers:
      - name: churnset-container
        image: eakpan15/churn-dashboard:0.0.1
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 1
            memory: 3G

