apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-prediction-training
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-script
            image: eakpan15/churn-dashboard:0.0.1
            command: ["python", "modeling/batch_model_training.py"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1