apiVersion: batch/v1
kind: CronJob
metadata:
  name: synthetic-data-gen
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-script
            image: eakpan15/churn-dashboard:0.0.1
            command: ["python", "database/synthetic_data.py"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1