apiVersion: batch/v1
kind: CronJob
metadata:
  name: synthetic-data-gen
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-script
            image: eakpan15/churn-dashboard:0.0.1
            command: ["python", "database/synthetic_data.py"]
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: example-script-configmap
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1