apiVersion: batch/v1
kind: CronJob
metadata:
  name: modeling-pipelines
spec:
  schedule: "*/20 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: modeling-pipelines-container
            image: eakpan15/churn-dashboard:0.0.1
            command: ["python", "modeling/modeling_pipelines.py"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1