apiVersion: v1
kind: Service
metadata:
  name: churnset-np-service
  namespace: churnset-namespace
spec:
  type: NodePort
  selector:
    app: churnset-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007